### ISSUE TITLE
Feature request: Highlight code 

### ISSUE THREAD

**Issue by zihaozhihao** [zhu-y/markdown-toolkit#14]
![Screenshot from 2019-04-24 09-16-17](https://user-images.githubusercontent.com/34079402/56675752-be351c00-6671-11e9-8fdd-de1331ed7a81.png)

It's better look like this if possible, 
```python
def norm_multi_hot(v):
    s = sum(v)
    return [i/s for i in v]
```
The current code highlight is all red color, which is not good to view the code.

**Comment by hk-mp5a3** [comment]
resolved
